{
 "title": "Monsoon Metrics",
 "time": { "from": "now-1h", "to": "now-45s" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "all_nodes",
    "label": "all_nodes",
    "query": "cn1_nauhpc,cn2_nauhpc,cn3_nauhpc,cn4_nauhpc,cn5_nauhpc,cn6_nauhpc,cn7_nauhpc,cn8_nauhpc,cn9_nauhpc,cn10_nauhpc,cn11_nauhpc,cn12_nauhpc,cn13_nauhpc,cn14_nauhpc,cn15_nauhpc,cn16_nauhpc,cn17_nauhpc,cn18_nauhpc,cn19_nauhpc,cn20_nauhpc,cn21_nauhpc,cn22_nauhpc,cn23_nauhpc,cn24_nauhpc,cn25_nauhpc,cn26_nauhpc,cn27_nauhpc,cn28_nauhpc,cn29_nauhpc,cn30_nauhpc,cn31_nauhpc,cn32_nauhpc,cn33_nauhpc,cn34_nauhpc,cn35_nauhpc,cn36_nauhpc,cn37_nauhpc,cn38_nauhpc,cn39_nauhpc,cn40_nauhpc,cn41_nauhpc,cn42_nauhpc,cn43_nauhpc,cn44_nauhpc,cn45_nauhpc,cn46_nauhpc,cn47_nauhpc,cn48_nauhpc,cn49_nauhpc,cn50_nauhpc,cn51_nauhpc,cn52_nauhpc,cn53_nauhpc,cn54_nauhpc,cn55_nauhpc,cn56_nauhpc,cn57_nauhpc,cn58_nauhpc,cn59_nauhpc,cn60_nauhpc,cn61_nauhpc,cn62_nauhpc,cn63_nauhpc,cn64_nauhpc,cn65_nauhpc,cn66_nauhpc,cn67_nauhpc,cn68_nauhpc,cn69_nauhpc,cn70_nauhpc,cn71_nauhpc,cn72_nauhpc,cn73_nauhpc,cn74_nauhpc,cn75_nauhpc,cn76_nauhpc,cn77_nauhpc,cn78_nauhpc,cn79_nauhpc,cn80_nauhpc,cn81_nauhpc,cn82_nauhpc,cn83_nauhpc,cn84_nauhpc,cn85_nauhpc,cn86_nauhpc,cn87_nauhpc,cn88_nauhpc,cn89_nauhpc,cn90_nauhpc,cn91_nauhpc,cn92_nauhpc,cn93_nauhpc,cn94_nauhpc,cn95_nauhpc,cn96_nauhpc,cn97_nauhpc,cn98_nauhpc,cn99_nauhpc,cn100_nauhpc,cn101_nauhpc,cn102_nauhpc,cn103_nauhpc,cn104_nauhpc,cn105_nauhpc,cn106_nauhpc,cn107_nauhpc,cn108_nauhpc"
   },
   {
    "name": "all_gpus",
    "label": "all_gpus",
    "query": "cn1_nauhpc.gpu.v100.0,cn1_nauhpc.gpu.v100.1,cn1_nauhpc.gpu.v100.2,cn1_nauhpc.gpu.v100.3,cn2_nauhpc.gpu.a100.0,cn2_nauhpc.gpu.a100.1,cn2_nauhpc.gpu.a100.2,cn3_nauhpc.gpu.a100.0,cn3_nauhpc.gpu.a100.1,cn3_nauhpc.gpu.a100.2,cn3_nauhpc.gpu.a100.3,cn31_nauhpc.gpu.k80.0,cn31_nauhpc.gpu.k80.1,cn31_nauhpc.gpu.k80.2,cn31_nauhpc.gpu.k80.3,cn32_nauhpc.gpu.k80.0,cn32_nauhpc.gpu.k80.1,cn32_nauhpc.gpu.k80.2,cn32_nauhpc.gpu.k80.3,cn32_nauhpc.gpu.k80.4,cn32_nauhpc.gpu.k80.5,cn32_nauhpc.gpu.k80.6,cn32_nauhpc.gpu.k80.7,cn33_nauhpc.gpu.p100.0,cn33_nauhpc.gpu.p100.1,cn33_nauhpc.gpu.p100.2,cn33_nauhpc.gpu.p100.3"
   },
   {
    "name": "gpu_metric",
    "label": "gpu_metric",
    "query": "temp,gpu_util,mem_util,mem_total,mem_free,mem_used"
   }
  ]
 },
 "panels": [
  { "title": "Aggregate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load vs Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "target": "sumSeries(cn*_nauhpc.cpu.count)"
    },
    {
     "target": "sumSeries(cn*_nauhpc.load.load.shortterm)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.cpus.allocated)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "target": "averageSeries(cn*_nauhpc.aggregation.cpu-average.percent.user)"
    },
    {
     "target": "averageSeries(cn*_nauhpc.aggregation.cpu-average.percent.nice)"
    },
    {
     "target": "averageSeries(cn*_nauhpc.aggregation.cpu-average.percent.system)"
    },
    {
     "target": "averageSeries(cn*_nauhpc.aggregation.cpu-average.percent.wait)"
    }
   ]
  },
  {
   "title": "Memory Utilization vs Allocated",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "target": "divideSeries(sumSeries(cn*_nauhpc.memory.memory.used), sumSeries(cn*_nauhpc.memory.memory.*))"
    },
    {
     "target": "divideSeries(sumSeries(slurm.sinfo.core.*.*.*.*.mem.allocated), sumSeries(slurm.sinfo.core.*.*.*.*.mem.total))"
    }
   ]
  },
  {
   "title": "GPU Utilization vs Allocated (Core Partition)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "scale(sumSeries(cn1_nauhpc.gpu.*.*.gpu_util, cn3_nauhpc.gpu.*.*.gpu_util, cn3._nauhpc.gpu.*.*.gpu_util), 0.01)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.gpus.allocated)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.gpus.total)"
    }
   ]
  },
  {
   "title": "Aggregate Network Throughput (eno1)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scale(sumSeries(perSecond(cn*_nauhpc.interface.eno1.if_octets.rx)), 8)"
    },
    {
     "target": "scale(sumSeries(perSecond(cn*_nauhpc.interface.eno1.if_octets.tx)), 8)"
    }
   ]
  },
  {
   "title": "Aggregate Network Throughput (ib0)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scale(sumSeries(perSecond(cn*_nauhpc.interface.ib0.if_octets.rx)), 8)"
    },
    {
     "target": "scale(sumSeries(perSecond(cn*_nauhpc.interface.ib0.if_octets.tx)), 8)"
    }
   ]
  },
  {
   "title": "Node Allocation (Core Partition)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.allocated)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.unknown)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.mixed)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.maint)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.draining)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.drained)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.down)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.completing)"
    },
    {
     "target": "sumSeries(slurm.sinfo.core.*.*.*.*.nodes.idle)"
    }
   ]
  },
  {
   "title": "Job Delay Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "target": "slurm.srun.estimated_delay.1" },
    { "target": "slurm.srun.estimated_delay.2" },
    { "target": "slurm.srun.estimated_delay.4" },
    { "target": "slurm.srun.estimated_delay.8" },
    { "target": "slurm.srun.estimated_delay.16" },
    { "target": "slurm.srun.estimated_delay.32" },
    { "target": "slurm.srun.estimated_delay.64" },
    {
     "target": "slurm.squeue.pending_time.median"
    },
    {
     "target": "slurm.squeue.pending_time.average"
    }
   ]
  },
  {
   "title": "Load and Mem For Each Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "$all_nodes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
     "repeat": "all_nodes",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "target": "divideSeries($all_nodes.load.load.shortterm, $all_nodes.cpu.count)"
      },
      {
       "target": "divideSeries($all_nodes.memory.memory.used, sumSeries($all_nodes.memory.memory.*))"
      }
     ]
    }
   ]
  },
  {
   "title": "GPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPU: $gpu_metric",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 37 },
     "repeat": "all_gpus",
     "targets": [
      { "target": "$all_gpus.$gpu_metric" }
     ]
    }
   ]
  },
  {
   "title": "Slurm Scheduling Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "jobs submitted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      { "target": "slurm.sdiag.jobs.submitted" },
      {
       "target": "aliasSub(aliasSub(aliasByNode(nonNegativeDerivative(slurm.sdiag.jobs.submitted), 4, 5), '\\.', ' '), '(.*)', '\\1 per second')"
      }
     ]
    },
    {
     "title": "jobs started",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      { "target": "slurm.sdiag.jobs.started" },
      {
       "target": "aliasSub(aliasSub(aliasByNode(nonNegativeDerivative(slurm.sdiag.jobs.started), 4, 5), '\\.', ' '), '(.*)', '\\1 per second')"
      }
     ]
    },
    {
     "title": "jobs completed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      { "target": "slurm.sdiag.jobs.completed" },
      {
       "target": "aliasSub(aliasSub(aliasByNode(nonNegativeDerivative(slurm.sdiag.jobs.completed), 4, 5), '\\.', ' '), '(.*)', '\\1 per second')"
      }
     ]
    },
    {
     "title": "jobs cancelled",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      { "target": "slurm.sdiag.jobs.canceled" },
      {
       "target": "aliasSub(aliasSub(aliasByNode(nonNegativeDerivative(slurm.sdiag.jobs.canceled), 4, 5), '\\.', ' '), '(.*)', '\\1 per second')"
      }
     ]
    },
    {
     "title": "server threads / agent queue",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short", "label": "queue size" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.agent_queue_size, 'agent queue size')"
      },
      {
       "target": "alias(slurm.sdiag.thread_count, 'server thread count')"
      }
     ]
    },
    {
     "title": "last cycle time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.main.last_cycle_usec, 'time for last scheduling cycle')"
      },
      {
       "target": "alias(slurm.sdiag.scheduler.main.mean_cycle_usec, 'scheduling cycle mean time')"
      },
      {
       "target": "alias(slurm.sdiag.scheduler.main.max_cycle_usec, 'scheduling cycle max time')"
      }
     ]
    },
    {
     "title": "cycles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.main.total_cycles, 'number of scheduling cycles')"
      },
      {
       "target": "alias(nonNegativeDerivative(slurm.sdiag.scheduler.main.total_cycles), 'scheduling cycles per second')"
      }
     ]
    },
    {
     "title": "processed / pending jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.main.mean_depth_cycle, 'average jobs processed in a scheduling cycle')"
      },
      {
       "target": "alias(slurm.sdiag.scheduler.main.last_queue_length, 'length of jobs pending queue')"
      }
     ]
    },
    {
     "title": "backfilled jobs",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.total_bf_jobs, 'jobs backfilled since last Slurm start')"
      },
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.total_bf_jobs_since_reset, 'jobs backfilled since last stats cycle start')"
      },
      {
       "target": "alias(nonNegativeDerivative(slurm.sdiag.scheduler.backfill.total_bf_jobs_since_reset), 'jobs backfilled per second')"
      }
     ]
    },
    {
     "title": "backfill cycle time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.last_cycle_usec, 'last backfilling cycle time')"
      },
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.mean_cycle_usec, 'mean backfilling cycle time')"
      }
     ]
    },
    {
     "title": "last depth cycle",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.last_depth_cycle, 'processed jobs in last backfill cycle')"
      },
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.last_depth_cycle_try, 'processed jobs in last backfill cycle (try sched)')"
      }
     ]
    },
    {
     "title": "backfill queue length",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
     "yaxes": [
      { "format": "none", "label": "jobs" }
     ],
     "targets": [
      {
       "target": "alias(slurm.sdiag.scheduler.backfill.last_queue_length, 'jobs pending backfill processing')"
      }
     ]
    }
   ]
  }
 ]
}